project:
  type: book
repo-url: https://github.com/nhs-r-community/r4ds-ed2-exercise-solutions
  repo-branch: main
  repo-actions: [edit, issue]
book:
  title: "R for Data Science (2nd edition) Exercise Solutions"
  author: "NHS-R Community"
  date: "24/04/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
